feature: copy cURL
syedmurtaza108/chucker-flutter pull request #87
Opened 2024-09-09 05:09 UTC by SyifaAinnur

## Description

Added copy curl function to detail inspector according to response

example of curl results

GET :
curl -i \
	-d "{userId: 1, id: 1, title: sunt aut facere repellat provident occaecati excepturi optio reprehenderit, body: quia et suscipit
suscipit recusandae consequuntur expedita et cum
reprehenderit molestiae ut ut quas totam
nostrum rerum est autem sunt rem eveniet architecto}" \
	"https://jsonplaceholder.typicode.com/posts/1"
	
POST :
curl -i \
	-X POST \
	-H "content-type: text/plain; charset=utf-8" \
	-d "{id: 101}" \
	"https://jsonplaceholder.typicode.com/posts"
	
PUT :
curl -i \
	-X PUT \
	-H "content-type: application/x-www-form-urlencoded; charset=utf-8" \
	-d "{title: PUT foo, body: PUT bar, userId: 101010, id: 1}" \
	"https://jsonplaceholder.typicode.com/posts/1"
	
	
![image](https://github.com/user-attachments/assets/91cca782-5bf0-4cbc-9e46-f59c2794e833)

## Type of Change

- [x ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2024-09-09 06:08 UTC, bwcr commented
This is a great way to handle things when testers discover problems and pass them on to developers for more explanation.

2024-09-09 06:22 UTC, syedmurtaza108 commented
@SyifaAinnur Thank you adding this PR. Can you please look into the failed action (https://github.com/syedmurtaza108/chucker-flutter/pull/87/checks). Flutter analyze command is failing. Mostly analayzer issues can be fixed using `dart fix --apply` command.

2024-09-09 06:47 UTC, SyifaAinnur commented
@syedmurtaza108  how  to fix the failed action in flutter test ?

2024-09-09 08:49 UTC, SyifaAinnur commented
@syedmurtaza108 how to fix the failed action in test ?, can you help me how to resolve it ?

2024-09-09 14:24 UTC, syedmurtaza108 commented
@SyifaAinnur I believe some actions are failing because of Flutter's version used in this repo. I will look into it. Don't worry.

2024-09-11 03:18 UTC, syedmurtaza108 requested changes

2024-09-11 03:18 UTC, syedmurtaza108 commented on lib/src/interceptors/chopper_interceptor.dart
> +        // headers: response.base.headers.toString(),
Can you please make sure that no commented out code is left in the PR.

2024-09-11 03:18 UTC, syedmurtaza108 commented on lib/src/view/api_detail_page.dart
> +String _cURLRepresentation(ApiResponse api) {
Can you please write some test cases for cURL feature?

2024-09-11 03:20 UTC, syedmurtaza108 commented
@SyifaAinnur Please add widget and unit tests for the feature you added. See codecov comment https://github.com/syedmurtaza108/chucker-flutter/pull/87#issuecomment-2342530464.

2024-09-11 10:29 UTC, syedmurtaza108 commented
@SyifaAinnur Flutter analyze command failed.

2024-09-12 02:59 UTC, syedmurtaza108 approved these changes

2024-09-12 02:59 UTC, merged

2024-09-12 04:04 UTC, syedmurtaza108 commented
@SyifaAinnur Thanks for adding this feature. As a token of appreciation, I have added you in the README file of this repo.